language: cpp

os:
  - linux
  - osx

dist: focal

osx_image: xcode12

compiler:
  - gcc
  - clang

arch:
    - amd64
    - ppc64le
    - s390x

addons:
  apt:
    packages:
      - libboost-all-dev
      - language-pack-en
      - language-pack-da
      - language-pack-nl
      - libboost-tools-dev
      - xsltproc
      - doxygen
      - docbook-xsl
      - default-jdk
      - fop

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update           ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install make     ; fi

script:
  - ./configure
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then gmake; else make; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then gmake test; else make test; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo gmake install; else sudo make install; fi

jobs:
  allow_failures:
    - os: osx

