.TH libzeep 3 "10-mar-2021" "version 5.1" "subroutine"
.SH NAME
libzeep \- A C++ library for working with XML, XPath, JSON, SOAP and REST servers and web applications
.SH NOTE
See HTML pages for more up-to-date documentation. E.g. at
\fIhttps://www.hekkelman.com/libzeep-doc/\fR or the documentation
installed at your local disk.
.SH DESCRIPTION
This library is a Swiss army knife for building web applications in C++. It contains
a validating XML parser, XPath support, JSON parser and webserver.
.sp
The webserver implementation was loosly inspired by Spring. It works with the concept
of controllers that handle requests to parts in the URL namespace. Three specializations
are available, for handling plain HTML, REST and SOAP requests respectively.
.sp
The HTML controller can use templating. This code is a clean room reimplementation of
the Thymeleaf template processing engine that comes with Spring.
.sp
Support for security in the form of JWT is available too.
.SH BUGS
Undoubtedly libzeep will contain bugs. Please report any bug you find to maarten@hekkelman.com
